[settings]
seeds = false
skip-lint = false

[programs.localnet]
motion_companion = "9xQeWvG816bUx9EPjHmaT23yvVM2ZWbrrpZb9PusVFU"

[programs.devnet]
motion_companion = "9xQeWvG816bUx9EPjHmaT23yvVM2ZWbrrpZb9PusVFU"

[programs.mainnet]
motion_companion = "9xQeWvG816bUx9EPjHmaT23yvVM2ZWbrrpZb9PusVFU"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
